// Credit-terms demos — the score with economic consequence. Three parts, each
// runnable alone (npm run demo:credit -- part1|part2|part3|all):
//
//   part1  COLLATERAL + REDEMPTION — Lexica (score < 50, authentically punished
//          by our own reject demos) posts a 50% mirror-job collateral, does good
//          work, the main job settles and the worker releases the collateral.
//   part2  SLASH — a throwaway agent earns a real bad history (one rejected
//          job → score < 50), posts collateral, does bad work again → main job
//          rejected and the collateral is completed to the client (slashed).
//   part3  CREDIT — a fresh agent earns score >= 80 with four clean settles,
//          then is hired on credit terms: 30% direct advance + 70% escrow.
//
// All histories are real onchain jobs — nothing staged. Throwaway agent keys are
// persisted to gitignored backend/.env (never printed) so runs are idempotent.
import 'dotenv/config'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import {
  createPublicClient,
  createWalletClient,
  decodeEventLog,
  formatUnits,
  http,
  keccak256,
  parseAbi,
  parseUnits,
  toHex,
  zeroAddress,
  type Address,
} from 'viem'
import { generatePrivateKey, privateKeyToAccount } from 'viem/accounts'
import { erc8183Abi, registryAbi } from './lib/abi.js'
import {
  ARBITER_ADDRESS,
  ARC_RPC,
  arcTestnet,
  ERC8183_ADDRESS,
  EXPLORER_URL,
  JobStatus,
  LIVE_AGENT_ADDRESS,
  REGISTRY_ADDRESS,
  USDC_ADDRESS,
} from './lib/config.js'
import { collateralDescription, termsMarker } from './lib/credit.js'
import { enrich, enrichTampered, hashOutput, loadInputDataset, verify } from './lib/enrichment.js'
import { reasonHashOf } from './lib/judged.js'
import { saveDeliverable, setVerdict } from './lib/store.js'

const PRICE_6 = parseUnits('2', 6)
const COLLATERAL_6 = parseUnits('1', 6) // 50%
const ADVANCE_6 = parseUnits('0.6', 6) // 30%
const ESCROW_CREDIT_6 = parseUnits('1.4', 6) // 70%
const API = 'http://localhost:8787'
const ENV_PATH = fileURLToPath(new URL('../.env', import.meta.url))

const usdcAbi = parseAbi(['function approve(address spender, uint256 amount) returns (bool)', 'function transfer(address to, uint256 amount) returns (bool)'])
const pub = createPublicClient({ chain: arcTestnet, transport: http(ARC_RPC) })
const tx = (h: string) => `${EXPLORER_URL}/tx/${h}`
const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms))

function need(name: string): `0x${string}` {
  const v = process.env[name]
  if (!v) throw new Error(`${name} not set in backend/.env`)
  return v as `0x${string}`
}
/** Persist a throwaway key to gitignored .env (never printed); reuse if present. */
function ensureThrowawayKey(name: string): `0x${string}` {
  const existing = process.env[name]
  if (existing) return existing as `0x${string}`
  const key = generatePrivateKey()
  let txt = existsSync(ENV_PATH) ? readFileSync(ENV_PATH, 'utf8') : ''
  txt = `${txt.replace(/\s*$/, '')}\n# Throwaway demo agent (testnet only, generated by demo-credit)\n${name}=${key}\n`
  writeFileSync(ENV_PATH, txt)
  process.env[name] = key
  return key
}

const wallet = (key: `0x${string}`) => createWalletClient({ account: privateKeyToAccount(key), chain: arcTestnet, transport: http(ARC_RPC) })
const client = wallet(need('DEMO_CLIENT_PRIVATE_KEY'))
const lexica = wallet(need('AGENT_LEXICA_PRIVATE_KEY'))
const arbiter = wallet(need('ARBITER_PRIVATE_KEY'))
const CLIENT = client.account.address
const getJob = (id: bigint) => pub.readContract({ address: ERC8183_ADDRESS, abi: erc8183Abi, functionName: 'getJob', args: [id] })

async function write(w: ReturnType<typeof wallet>, label: string, params: Parameters<typeof w.writeContract>[0]): Promise<`0x${string}`> {
  const hash = await w.writeContract(params)
  console.log(`  ${label}   ${tx(hash)}`)
  await pub.waitForTransactionReceipt({ hash })
  return hash
}

async function createJob(w: ReturnType<typeof wallet>, provider: Address, description: string): Promise<bigint> {
  const expiredAt = BigInt(Math.floor(Date.now() / 1000) + 7200)
  const hash = await w.writeContract({
    address: ERC8183_ADDRESS,
    abi: erc8183Abi,
    functionName: 'createJob',
    args: [provider, ARBITER_ADDRESS, expiredAt, description, zeroAddress],
  })
  const receipt = await pub.waitForTransactionReceipt({ hash })
  for (const lg of receipt.logs) {
    try {
      const d = decodeEventLog({ abi: erc8183Abi, topics: lg.topics, data: lg.data })
      if (d.eventName === 'JobCreated') {
        const id = (d.args as { jobId: bigint }).jobId
        console.log(`  createJob → job #${id}   ${tx(hash)}`)
        return id
      }
    } catch {
      /* not this event */
    }
  }
  throw new Error('JobCreated event not found')
}

async function waitStatus(id: bigint, wanted: number[], cycles = 60): Promise<number> {
  for (let i = 0; i < cycles; i++) {
    const s = Number((await getJob(id)).status)
    if (wanted.includes(s)) return s
    await sleep(5000)
  }
  throw new Error(`job #${id} never reached status ${wanted.join('/')}`)
}

/** Post the mirror-job collateral: agent funds, client is provider, arbiter is
 * evaluator; a placeholder submit makes it settleable from Submitted. */
async function postCollateral(agentW: ReturnType<typeof wallet>, agentAddr: Address): Promise<bigint> {
  console.log('— posting collateral (mirror job on the reference contract) —')
  const colId = await createJob(agentW, CLIENT, collateralDescription(agentAddr, formatUnits(COLLATERAL_6, 6)))
  await write(client, `client setBudget #${colId} = 1 USDC`, { address: ERC8183_ADDRESS, abi: erc8183Abi, functionName: 'setBudget', args: [colId, COLLATERAL_6, '0x'] })
  await write(agentW, `agent approve exact 1 USDC`, { address: USDC_ADDRESS, abi: usdcAbi, functionName: 'approve', args: [ERC8183_ADDRESS, COLLATERAL_6] })
  await write(agentW, `agent fund collateral #${colId} (1 USDC locked in Circle's escrow)`, { address: ERC8183_ADDRESS, abi: erc8183Abi, functionName: 'fund', args: [colId, '0x'] })
  await write(client, `client submit collateral receipt`, { address: ERC8183_ADDRESS, abi: erc8183Abi, functionName: 'submit', args: [colId, keccak256(toHex('agentscore:collateral-receipt')), '0x'] })
  return colId
}

/** Script-driven agent work + arbiter verdict for non-Lexica agents (the worker
 * only automates Lexica). Mirrors the worker's deterministic path exactly. */
async function scriptedCycle(agentW: ReturnType<typeof wallet>, agentAddr: Address, opts: { tampered: boolean; description: string; escrow6: bigint }): Promise<bigint> {
  const jobId = await createJob(client, agentAddr, opts.description)
  await write(agentW, `agent setBudget ${formatUnits(opts.escrow6, 6)} USDC`, { address: ERC8183_ADDRESS, abi: erc8183Abi, functionName: 'setBudget', args: [jobId, opts.escrow6, '0x'] })
  await write(client, `client approve exact`, { address: USDC_ADDRESS, abi: usdcAbi, functionName: 'approve', args: [ERC8183_ADDRESS, opts.escrow6] })
  await write(client, `client fund escrow`, { address: ERC8183_ADDRESS, abi: erc8183Abi, functionName: 'fund', args: [jobId, '0x'] })

  const input = loadInputDataset()
  const output = opts.tampered ? enrichTampered(input) : enrich(input)
  const outputHash = hashOutput(output)
  saveDeliverable({ jobId: jobId.toString(), producedBy: agentAddr, spec: 'dedupe wallet dataset by address + risk-label each row', inputRows: input.length, output, outputHash, createdAt: Math.floor(Date.now() / 1000) })
  const submitTx = await write(agentW, `agent submit (${output.length} rows${opts.tampered ? ', TAMPERED' : ''})`, { address: ERC8183_ADDRESS, abi: erc8183Abi, functionName: 'submit', args: [jobId, outputHash, '0x'] })

  const result = verify(input, output, outputHash)
  const nowSec = Math.floor(Date.now() / 1000)
  if (result.ok) {
    const reason = keccak256(toHex(`agentscore:verified:job-${jobId}`))
    const settleTx = await write(arbiter, `arbiter VERIFIED — complete`, { address: ERC8183_ADDRESS, abi: erc8183Abi, functionName: 'complete', args: [jobId, reason, '0x'] })
    await write(arbiter, `arbiter attest APPROVED`, { address: REGISTRY_ADDRESS, abi: registryAbi, functionName: 'attest', args: [jobId, agentAddr, 0, reason] })
    setVerdict(jobId.toString(), { outcome: 'approved', checks: result.checks, expectedRowCount: result.expectedRowCount, gotRowCount: result.gotRowCount, verifiedAt: nowSec, settleTx })
  } else {
    const reason = keccak256(toHex(`agentscore:rejected-badwork:job-${jobId}`))
    const settleTx = await write(arbiter, `arbiter REJECTED — refund`, { address: ERC8183_ADDRESS, abi: erc8183Abi, functionName: 'reject', args: [jobId, reason, '0x'] })
    await write(arbiter, `arbiter attest REJECTED`, { address: REGISTRY_ADDRESS, abi: registryAbi, functionName: 'attest', args: [jobId, agentAddr, 1, reason] })
    setVerdict(jobId.toString(), { outcome: 'rejected', checks: result.checks, expectedRowCount: result.expectedRowCount, gotRowCount: result.gotRowCount, verifiedAt: nowSec, settleTx })
  }
  void submitTx
  return jobId
}

async function apiScore(addr: string): Promise<number> {
  try {
    const res = await fetch(`${API}/agent/${addr}`)
    if (!res.ok) return -1
    const j = (await res.json()) as { score: number }
    return j.score
  } catch {
    return -1
  }
}

async function seedGas(to: Address, usdc: string) {
  await write(lexica, `Lexica seeds ${usdc} USDC to ${to.slice(0, 8)}… (gas + collateral)`, { address: USDC_ADDRESS, abi: usdcAbi, functionName: 'transfer', args: [to, parseUnits(usdc, 6)] })
}

// ---- part 1: Lexica collateral + redemption (worker-automated main job) -----
async function part1() {
  const score = await apiScore(LIVE_AGENT_ADDRESS)
  console.log(`\n=== PART 1 — collateral + redemption: Lexica (live score ${score}) ===`)
  if (score >= 50) console.log('note: Lexica is no longer < 50 — running anyway as an explicit collateral demo')
  const colId = await postCollateral(lexica, LIVE_AGENT_ADDRESS)
  console.log('— main job (worker-automated: gate → work → verdict → collateral release) —')
  const mainId = await createJob(
    client,
    LIVE_AGENT_ADDRESS,
    `Enrich the wallet dataset: dedupe by address and risk-label each row. ${termsMarker({ tier: 'collateral', score: score >= 0 ? score : undefined, collateralJobId: colId })}`,
  )
  // The worker sets the budget; the client funds; the worker gate verifies the
  // collateral before any work happens.
  await waitStatus(mainId, [JobStatus.Open], 30)
  for (let i = 0; i < 30; i++) {
    if (await pub.readContract({ address: ERC8183_ADDRESS, abi: erc8183Abi, functionName: 'jobHasBudget', args: [mainId] })) break
    await sleep(4000)
  }
  await write(client, `client approve exact 2 USDC`, { address: USDC_ADDRESS, abi: usdcAbi, functionName: 'approve', args: [ERC8183_ADDRESS, PRICE_6] })
  await write(client, `client fund escrow`, { address: ERC8183_ADDRESS, abi: erc8183Abi, functionName: 'fund', args: [mainId, '0x'] })
  const s = await waitStatus(mainId, [JobStatus.Completed, JobStatus.Rejected])
  console.log(s === JobStatus.Completed ? `✅ main #${mainId} settled` : `❌ main #${mainId} rejected (unexpected)`)
  const colFinal = await waitStatus(colId, [JobStatus.Completed, JobStatus.Rejected])
  console.log(colFinal === JobStatus.Rejected ? `↩ collateral #${colId} RELEASED back to Lexica (refund path)` : `⚔ collateral #${colId} slashed (unexpected)`)
  console.log(`job pages: /job/${mainId} · /job/${colId} — Lexica score now ${await apiScore(LIVE_AGENT_ADDRESS)} (redemption: +8 on a clean settle)`)
}

// ---- part 2: real bad history → collateral → slash --------------------------
async function part2() {
  const badKey = ensureThrowawayKey('BAD_AGENT_PRIVATE_KEY')
  const bad = wallet(badKey)
  const BAD = bad.account.address
  console.log(`\n=== PART 2 — slash: throwaway agent ${BAD.slice(0, 10)}… earns a real bad history ===`)
  const bal = await pub.readContract({ address: USDC_ADDRESS, abi: parseAbi(['function balanceOf(address) view returns (uint256)']), functionName: 'balanceOf', args: [BAD] })
  if (bal < parseUnits('1.5', 6)) await seedGas(BAD, '2')

  let score = await apiScore(BAD)
  if (score < 0 || score >= 50) {
    console.log(`— building a real bad history (current score ${score < 0 ? 'n/a' : score}): one tampered job → reject → −20 —`)
    await scriptedCycle(bad, BAD, { tampered: true, description: 'Enrich the wallet dataset: dedupe by address and risk-label each row.', escrow6: PRICE_6 })
    score = await apiScore(BAD)
  }
  console.log(`bad agent live score: ${score} → collateral tier`)

  const colId = await postCollateral(bad, BAD)
  console.log('— main job: bad work with collateral at stake —')
  const mainId = await scriptedCycle(bad, BAD, {
    tampered: true,
    description: `Enrich the wallet dataset: dedupe by address and risk-label each row. ${termsMarker({ tier: 'collateral', score, collateralJobId: colId })}`,
    escrow6: PRICE_6,
  })
  console.log('— slashing: main rejected → arbiter completes the mirror job, paying the client —')
  const reason = reasonHashOf(`Collateral slashed: main job #${mainId} was rejected.`)
  await write(arbiter, `arbiter slash collateral #${colId} → client`, { address: ERC8183_ADDRESS, abi: erc8183Abi, functionName: 'complete', args: [colId, reason, '0x'] })
  console.log(`⚔ collateral #${colId} (1 USDC) forfeited to the client. Bad agent score now ${await apiScore(BAD)}.`)
  console.log(`job pages: /job/${mainId} · /job/${colId}`)
}

// ---- part 3: earn score >= 80, then hire on credit terms --------------------
async function part3() {
  const primeKey = ensureThrowawayKey('PRIME_AGENT_PRIVATE_KEY')
  const prime = wallet(primeKey)
  const PRIME = prime.account.address
  console.log(`\n=== PART 3 — credit: agent ${PRIME.slice(0, 10)}… earns its terms ===`)
  const bal = await pub.readContract({ address: USDC_ADDRESS, abi: parseAbi(['function balanceOf(address) view returns (uint256)']), functionName: 'balanceOf', args: [PRIME] })
  if (bal < parseUnits('0.4', 6)) await seedGas(PRIME, '0.5')

  let score = await apiScore(PRIME)
  let cycles = 0
  while (score < 80 && cycles < 6) {
    console.log(`— clean settle ${cycles + 1} (score ${score < 0 ? 'n/a' : score}) —`)
    await scriptedCycle(prime, PRIME, { tampered: false, description: 'Enrich the wallet dataset: dedupe by address and risk-label each row.', escrow6: PRICE_6 })
    await sleep(3000)
    score = await apiScore(PRIME)
    cycles++
  }
  console.log(`prime agent live score: ${score} ${score >= 80 ? '→ credit tier ✓' : '(did not reach 80 — stopping)'}`)
  if (score < 80) return

  console.log('— credit hire: 30% advance paid directly, 70% escrowed —')
  const advanceTx = await write(client, `client pays advance 0.6 USDC directly to the agent (working capital)`, { address: USDC_ADDRESS, abi: usdcAbi, functionName: 'transfer', args: [PRIME, ADVANCE_6] })
  const mainId = await scriptedCycle(prime, PRIME, {
    tampered: false,
    description: `Enrich the wallet dataset: dedupe by address and risk-label each row. ${termsMarker({ tier: 'credit', score, advanceTx })}`,
    escrow6: ESCROW_CREDIT_6,
  })
  console.log(`✅ credit job #${mainId}: agent held 0.6 USDC before working; 1.4 USDC released on completion. Total 2 USDC, ${await apiScore(PRIME)} score.`)
  console.log(`job page: /job/${mainId}`)
}

const which = (process.argv[2] || 'all').toLowerCase()
if (which === 'part1' || which === 'all') await part1()
if (which === 'part2' || which === 'all') await part2()
if (which === 'part3' || which === 'all') await part3()
process.exit(0)
